---
title: "What proportion of each occupation have made EI claims?"
subtitle: "COVID impacts"
output: html_notebook
---


```{r setup}
library(tidyverse)
library(glue)
library(lubridate)
library(readxl)
```

## LFS data

(see "scr\LFS\LFS_occupation.Rmd" for details)

```{r}

df_1410029601 <- read_rds(here::here("data", "df_1410029601.rds"))

# filter BC employment at 2 digit NOC
df_lfs_bc_noc2 <- df_1410029601 %>% 
  filter(geo == "British Columbia",
         labour_force_characteristics == "Employment",
         sex == "Both sexes") %>% 
  rename("noc_code" = classification_code_for_national_occupational_classification_noc) %>% 
  filter(str_detect(noc_code, "\\[\\d{2}\\]"))

write_rds(df_lfs_bc_noc2, here::here("data", "df_lfs_bc_noc2.rds"))

df_lfs_bc_noc2

```


```{r}

df_lfs_bc_noc2_2020_03 <-
df_lfs_bc_noc2 %>% 
  select(ref_date, 
         national_occupational_classification_noc, 
         noc_code,
         value) %>% 
  group_by(noc_code) %>% 
  mutate(prv_mon = lag(value, 1),
         chg_mom = value - prv_mon,
         pctchg_mom = chg_mom/prv_mon) %>% 
  ungroup() %>% 
  filter(ref_date == "2020-03")

df_lfs_bc_noc2_2020_03

write_csv(df_lfs_bc_noc2_2020_03, here::here("data", "df_lfs_bc_noc2_2020_03.csv"))

```



## EI

```{r}
df_ei <- read_excel(here::here("data", "2A73-DAS-EIApplicants_BC_20200301to202000426--2A73-DIR-20200427-VF-AK.xlsx"),
                    sheet = "By NOC - Par CNP")

df_ei_noc <- df_ei %>% 
  select(-`...3`, -`Total`) %>% 
  rename("noc4" = `Appliweb Applicants/Candidats de l'Appliweb`,
         "noc4_desc" = `...2`) %>% 
  filter(noc4 != "Total") %>% 
  mutate("noc2" = str_sub(noc4, 1, 2)) %>% 
  select(noc2, everything()) %>% 
  pivot_longer(cols = -(noc2:noc4_desc), names_to = "date_week", values_to = "ei_app_count") %>% 
  mutate("month_app" = str_sub(date_week, 4, 5))


write_rds(df_ei_noc, here::here("data", "df_ei_noc.rds"))

#df_ei_noc <- read_rds(here::here("data", "df_ei_noc.rds"))

```


## summary statistics

```{r}
# total over period, by 4 digit NOC (i.e. column M in table)
df_ei_noc %>% 
  group_by(noc4) %>% 
  summarise(total_ei = sum(ei_app_count, na.rm = TRUE)) %>% 
  arrange(desc(total_ei))


# total over period, by 2 digit NOC
df_ei_noc %>% 
  group_by(noc2) %>% 
  summarise(total_ei = sum(ei_app_count, na.rm = TRUE)) %>% 
  arrange(desc(total_ei))

# total single month, by 2 digit NOC
df_ei_March <- df_ei_noc %>%
  filter(month_app == "03") %>% 
  group_by(noc2) %>% 
  summarise(total_ei = sum(ei_app_count, na.rm = TRUE)) %>% 
  arrange(noc2) %>% 
  mutate(noc2 = as.character(glue("[{noc2}]")))

df_ei_March

```


## Analysis

### Compare March EI to February LFS


```{r}

df_est_pct <- 
df_lfs_bc_noc2 %>% 
  filter(ref_date == "2020-02") %>% 
  right_join(df_ei_March, by = c("noc_code" = "noc2")) %>% 
  select(ref_date, 
         national_occupational_classification_noc, noc_code,
         value,
         total_ei) %>% 
  mutate(pct_ei = total_ei / (value * 1000))

df_est_pct

write_csv(df_est_pct, here::here("data", "df_est_pct.csv"))

```



```{r}

df_est_pct_2 <-
df_lfs_bc_noc2_2020_03 %>% 
  right_join(df_ei_March, by = c("noc_code" = "noc2")) %>% 
  mutate(pct_ei = total_ei / (value * 1000))


write_csv(df_est_pct_2, here::here("data", "df_est_pct_2.csv"))


```

