---
title: "Survey of Manufacturing"
author: "Martin Monkman"
date: "September 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This set of scripts creates summary tables and graphs plotting the Monthly Survey of Manufacturing data collected and reported by Statistics Canada.

#### packages

```{r}

# tidyverse
library(tidyverse)
#library(readr)
#library("ggplot2") # NOTE: requires ggplot 2.2.0 
#library("dplyr")

# monthly data series
library(zoo)
# extending ggplot2
library("scales")

# cansim
library(cansim)

```

---

The Daily, 2018-09-18

* https://www150.statcan.gc.ca/n1/daily-quotidien/180918/dq180918a-eng.htm 


### data

National
https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1610004701

Provincial (sales only)
https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1610004801


```{r}

#thedata <- read_csv("../data/03270056-eng.csv")

```


#### data wrangling

```{r}


# fix dates
class(thedata$Ref_Date)
thedata$DATE <- as.Date(as.yearmon(thedata$Ref_Date, format="%Y/%m"))
#

startdate <- as.Date("2007-01-01")


# filter to have BC and Canada
thedata_long <- thedata %>%
  filter(DATE >= startdate) %>%
  filter(GEO == c("British Columbia", "Canada"), INDEX == "Total (house and land)")

thedata_long


```

--- 

### plot


```{r}
# PLOT!
# basic
ggplot(thedata_long, aes(x=DATE, y=Value, group=GEO)) + 
  geom_line()
#
# with formatting applied
dataplot <- ggplot(thedata_long, aes(x=DATE, y=Value, colour=GEO)) + 
  geom_line(size=1.5) 
dataplot

```

with more formatting

```{r}

dataplot2 <- dataplot +
  #  ylim(3500000, 6500000) +
  scale_y_continuous(labels = comma, limits = c(80, 110)) +
  scale_colour_manual(name=NULL,
                      breaks=c("Canada", "British Columbia"),
                      labels=c("Canada", "British Columbia"), 
                      values=c("#325A80", "#CCB550")) +
  theme_bw() +
  theme(
    panel.border = element_rect(colour="white"),
    plot.title = element_text(face="bold"),
    legend.position=c(1,0), 
    legend.justification=c(1,0),
    legend.title = element_text(size=12),
    legend.text = element_text(size=11),
    axis.line = element_line(colour="black"),
    axis.title = element_text(size=12),
    axis.text = element_text(size=12)
  )
#
dataplot2 

```

final version

```{r}

# experiments with ggplot2's new subtitle and caption options

NHPI_title <- as.character("New Housing Price Index, Canada & B.C.")
NHPI_subtitle <- as.character("December 2016 = 100")
NHPI_caption <- as.character("Source: Statistics Canada, CANSIM table 327-0056")

# add titles / X-Y axis labels
dataplot2 +
  ggtitle(NHPI_title, subtitle = NHPI_subtitle)

# add titles / X-Y axis labels
dataplot2 +
  labs(title = NHPI_title, subtitle = NHPI_subtitle)

# add titles / X-Y axis labels
dataplot2 +
  labs(title = NHPI_title,
       subtitle = NHPI_subtitle,
       x = NULL, y = "NHPI")

# add titles / X-Y axis labels
dataplot2 +
  labs(title = NHPI_title,
       subtitle = NHPI_subtitle,
       caption = NHPI_caption, 
       x = NULL, y = "NHPI") 

# final version
# add titles / X-Y axis labels / caption
NHPI_plot <- dataplot2 +
  labs(title = NHPI_title,
       subtitle = NHPI_subtitle,
       caption = NHPI_caption, 
       x = NULL, y = "NHPI (Dec. 2016 = 100)") 

NHPI_plot

ggsave(filename = "NHPI_plot.png", plot = NHPI_plot,
       width = 8, height = 6)

```


