<!--
Copyright 2019 Province of British Columbia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
-->



---
title: "Employment by class of worker"
output: html_notebook
---

## Employment by class of worker

Employment by class of worker, annual (x 1,000)1

https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410002701

Table: 14-10-0027-01 (formerly CANSIM  282-0012)




### original script to pull and wrangle data

```{r}

library(CANSIM2R)
library(dplyr)
library(tidyr)

DF<-getCANSIM(14100027,raw="TRUE")
DF[[13]]<-as.numeric(as.character(DF[[13]]))
DF<-filter(DF, Sex=="Both sexes")
colnames(DF)[1]<-"t"
colnames(DF)[5]<-"NAICS"
DF<-DF[c("t","GEO","NAICS","Class.of.worker","VALUE")] 
DF<-DF[DF$t>2000,] # take data from 2001 on only
GEO<-unique(DF$GEO)
IND<-unique(DF$NAICS)
COW<-unique(DF$Class.of.worker)
i<-1 # region counter
while(i<=length(GEO)){
  j<-1 # industry counter
  while(j<=length(IND)){
    DF2<-filter(DF,GEO==GEO[[i]],NAICS==IND[[j]])
    DF2<-DF2[c("t","Class.of.worker","VALUE")] %>% spread(key="Class.of.worker",value="VALUE")
    DF2<-t(DF2[COW]) # re-sort by COW and transpose
    DF2<-data.frame(GEO=rep(GEO[[i]]),NAICS=rep(IND[[j]]),DF2)
    ifelse(exists('Table'),Table<-rbind(Table,DF2),Table<-DF2)
    j<-j+1
  }
  i<-i+1
}



```

```{r}
Table
```



### rewrite


```{r packages}

library(cansim)

library(dplyr)
library(tidyr)

```


```{r data_read}

# read the data 
DF_source <- get_cansim("14-10-0027-01")

DF_source

```


approximate what the original version is doing

```{r}

DF <- DF_source %>%
  filter(REF_DATE > 2000,
         Sex == "Both sexes") %>%
  select("t" = REF_DATE,
         "Class.of.worker" = `Class of worker`,
         "GEO",
         "NAICS" = `North American Industry Classification System (NAICS)`,
         "VALUE")

Table <- DF %>%
#  spread(key="Class.of.worker", value="VALUE")
  spread(key="t", value="VALUE")

Table

```

